### ISSUE TITLE
Stability issues

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [cyberneel/InfiniTime#8]
### Verification

- [X] I searched for similar issues (including closed issues) and found none was relevant.

### Introduce the issue

After 1 snooze and before the 2nd snoozr my watch rebooted today.

**Comment by thiswillbeyourgithub** [comment]
Btw I noticed that there seems to be two kind of stability issues as sometimes it reboots but sometimes it seems to reboot so hard that the date and time (so probably othet things too) get reset!

relevant to #9

**Comment by cyberneel** [comment]
I'll look into this, I think I fixed that bug.

Also, the two types are actually one I think. No other settings would be erased as those are stored to a file. The time is what changes if anything since that is dependent on the companion app to send. So the default time is 12, u til the companion app sends a correct time.

**Comment by thiswillbeyourgithub** [comment]
> I'll look into this, I think I fixed that bug

after flashing v9 i have no more reboots so far. Wil reopen if I do!
